dados_onibus = {

# LINHA 3356
    '3356 (T. Ibirité / Canaã Via Lago Azul) - Tarifa: R$ 6,60': {
        'Dia útil': {
            'horarios': [ "05:20", "05:20", "05:30", "05:42", "05:54", "06:00", "06:06", "06:18", "06:30", "06:40", "06:50", "07:00",
                "07:12", "07:24", "07:36", "07:48", "08:00", "08:20", "08:40", "09:00", "09:20", "09:40", "10:00", "10:20",
                "10:40", "11:00", "11:20", "11:40", "12:00", "12:20", "12:40", "13:00", "13:20", "13:40", "14:00", "14:20",
                "14:40", "15:00", "15:20", "15:40", "16:00", "16:20", "16:40", "16:50", "17:00", "17:12", "17:24", "17:36",
                "17:48", "18:00", "18:12", "18:24", "18:36", "18:48", "19:00", "19:10", "19:20", "19:30", "19:40", "20:00",
                "20:15"
            ],
            
            'pontos': {
                'Terminal Ibirité': 0,
                'Hospital': 2,
                'Fazenda do Rosário (Oposto a Pestalozzi)': 5,
                'ESSA/FHA/UEMG': 8,
                'Canal de Ibirité': 10,
                'B. LAGO AZUL': 12,
                'EE Professora Yolanda Martins': 15,
                'B. CANAÃ': 18,
                'Rua Tupã': 21,
                'Canal de Ibirité (VOLTA)': 24,
                'ESSA/FHA/UEMG (VOLTA)': 26,
                'Fazenda do Rosário (Oposto a Pestalozzi) (VOLTA)': 29,
                'Hospital (VOLTA)': 33,
                'Terminal Ibirité (VOLTA)': 35

            }
        },

        'Sábado': {
            'horarios': ["04:20", "04:30", "05:00", "05:20", "05:40", "06:00", "06:20", "06:40", 
 "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:40", 
 "11:20", "12:00", "12:40", "13:20", "14:00", "14:40", "15:20", "16:00", 
 "16:40", "17:20", "18:00", "18:30", "19:00"]
,
            'pontos': {
                'Terminal Ibirité': 0,
                'Hospital': 2,
                'Fazenda do Rosário (Oposto a Pestalozzi)': 5,
                'ESSA/FHA/UEMG': 8,
                'Canal de Ibirité': 10,
                'B. LAGO AZUL': 12,
                'EE Professora Yolanda Martins': 15,
                'B. CANAÃ': 18,
                'Rua Tupã': 21,
                'Canal de Ibirité (VOLTA)': 24,
                'ESSA/FHA/UEMG (VOLTA)': 26,
                'Fazenda do Rosário (Oposto a Pestalozzi) (VOLTA)': 29,
                'Hospital (VOLTA)': 33,
                'Terminal Ibirité (VOLTA)': 35
            }
        },
        'Domingo': {
            'horarios': ["05:00", "05:30", "06:00", "06:30", "07:00", "07:30", "08:00", "08:45", 
 "09:30", "10:15", "11:00", "11:45", "12:30", "13:15", "14:00", "14:45", 
 "15:00", "16:15", "17:00", "17:45", "18:30", "19:05"],
            'pontos': {
                'Terminal Ibirité': 0,
                'Hospital': 1,
                'Fazenda do Rosário (Oposto a Pestalozzi)': 4,
                'ESSA/FHA/UEMG': 7,
                'Canal de Ibirité': 8,
                'B. LAGO AZUL': 10,
                'EE Professora Yolanda Martins': 13,
                'B. CANAÃ': 15,
                'Rua Tupã': 19,
                'Canal de Ibirité (VOLTA)': 21,
                'ESSA/FHA/UEMG (VOLTA)': 24,
                'Fazenda do Rosário (Oposto a Pestalozzi) (VOLTA)': 26,
                'Hospital (VOLTA)': 20,
                'Terminal Ibirité (VOLTA)': 30
            }
        }
    },

#LINHA 3370
    '3370 (T. Ibirité / Canoas Via São Pedro) - Tarifa: R$ 6,60': {
        'Dia útil': {
            'horarios': ["06:30", "08:00", "09:30", "11:00", "13:00", "15:00", "16:30", "18:00", "19:00", "20:30"],
            'pontos': {
                'Terminal Ibirité': 0,
                'Hospital': 2,
                'Fazenda do Rosário (Oposto a Pestalozzi)': 5,
                'ESSA/FHA/UEMG': 8,
                'Canal de Ibirité': 10,
                'B. SÃO PEDRO': 12,
                'Complexo Esportivo do Canaã': 15,
                'Supermercado IZA': 17,
                'B. CANOAS': 20,
                'Antigo fim da linha 1003': 23,
                'R. Itajaí, 100': 26,
                'EE Professora Yolanda Martins': 27,
                'Canal de Ibirité (VOLTA)': 30,
                'ESSA/FHA/UEMG (VOLTA)': 32,
                'Fazenda do Rosário (Oposto a Pestalozzi) (VOLTA)': 35,
                'Hospital (VOLTA)': 37,
                'Terminal Ibirité (VOLTA)': 39

            }
        },
        'Sábado': {
            'horarios': ["04:50", "06:45", "08:45", "11:00", "13:20", "15:10", "16:30", "18:00", "20:30"],
            'pontos': {
                'Terminal Ibirité': 0,
                'Hospital': 2,
                'Fazenda do Rosário (Oposto a Pestalozzi)': 5,
                'ESSA/FHA/UEMG': 8,
                'Canal de Ibirité': 10,
                'B. SÃO PEDRO': 12,
                'Complexo Esportivo do Canaã': 15,
                'Supermercado IZA': 17,
                'B. CANOAS': 20,
                'Antigo fim da linha 1003': 23,
                'R. Itajaí, 100': 25,
                'EE Professora Yolanda Martins': 26,
                'Canal de Ibirité (VOLTA)': 28,
                'ESSA/FHA/UEMG (VOLTA)': 30,
                'Fazenda do Rosário (Oposto a Pestalozzi) (VOLTA)': 33,
                'Hospital (VOLTA)': 35,
                'Terminal Ibirité (VOLTA)': 37
            }
        },
        'Domingo': {
            'horarios': ["05:00", "06:30", "08:00", "11:00", "13:30", "15:00", "16:30", "18:00", "20:30"],
            'pontos': {
                'Terminal Ibirité ': 0,
                'Hospital': 1,
                'Fazenda do Rosário (Oposto a Pestalozzi)': 3,
                'ESSA/FHA/UEMG': 6,
                'Canal de Ibirité': 8,
                'B. SÃO PEDRO': 10,
                'Complexo Esportivo do Canaã': 15,
                'Supermercado IZA': 16,
                'B. CANOAS': 19,
                'Antigo fim da linha 1003': 22,
                'R. Itajaí, 100': 24,
                'EE Professora Yolanda Martins (VOLTA)': 26,
                'Canal de Ibirité (VOLTA)': 28,
                'ESSA/FHA/UEMG (VOLTA)': 31,
                'Fazenda do Rosário (Oposto a Pestalozzi) (VOLTA)': 33,
                'Hospital (VOLTA)': 34,
                'Terminal Ibirité (VOLTA)': 35
            }
        }
    },

#LINHA 304M
    '304M (T. Ibirité / Estação Eldorado Via BR-381) - Tarifa: R$ 9,55': {  
        'Dia útil': {
            'horarios': ["04:10", "04:35", "05:00", "05:15", "05:30", "05:40", "06:05", "06:35", 
 "08:00", "10:10", "12:20", "14:30", "16:00", "16:10", "17:00", "17:10", "18:50", "21:10"],
            'pontos': {
                'Terminal Ibirité': 0,
                'Perto da Prefeitura de Ibirité': 3,
                'Fórum de Ibirité': 6,
                'Ibirité Integrado': 9,
                'Hospital UPA': 12,
                'Fazenda do Rosário (Oposto a Pestalozzi)': 15,
                'Entrada Condomínio Quinta das Jangadas': 20,
                'B. LAGO AZUL': 21,
                'EE Professora Yolanda Martins': 26,
                'Rua Tupã, 555': 29,
                'B. SÃO PEDRO': 30,
                'Oposto ao Espaço ADAV': 36,
                'B. JARDIM DAS ROSAS': 30,
                'Perto de Magna/Thyssenkrupp': 35,
                'B. PETROVALE - BETIM (Rotatória Av. do Contorno)': 42,
                'GASMIG': 44,
                'Royal FIC': 47,
                'REGAP - Refinaria Gabriel Passos': 50,
                'CHEGADA À BR-381': 53,
                'Viaduto Torino': 57,
                'DEVA IVECO': 59,
                'CARREFOUR': 65,
                'Minas Máquinas - Mercedes-Benz': 70,
                'Jamef Transprtes': 76,
                'Viação Cometa': 80,
                'Leroy Merlin': 84,
                'Estação Eldorado': 87,
                'Marcopolo Contagem (VOLTA)': 97,
                'Estação Rio Nilo (VOLTA)': 102,
                'CARREFOUR (VOLTA)': 104,
                'DEVA IVECO (VOLTA)': 109,
                'Viaduto Torino (VOLTA)': 112,
                'SAÍDA DA BR-381': 117,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 120,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 125,
                'Perto de Magna/Thyssenkrupp': 129,
                'BAIRRO JARDIM DAS ROSAS (VOLTA)': 129,
                'Estação Eldorado': 87,
                'Leroy Merlin (VOLTA)': 90,
                'Minas Máquinas - Mercedes-Benz (VOLTA)': 104,
                'Estação Rio Nilo': 107,
                'CARREFOUR (VOLTA)': 108,
                'DEVA IVECO (VOLTA)': 113,
                'Viaduto Torino (VOLTA)': 117,
                'SAÍDA DA BR-381': 121,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 124,
                'Royal FIC (VOLTA)': 127,
                'GASMIG (VOLTA)': 130,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 132,
                'Perto de Magna/Thyssenkrupp (B. JARDIM DAS ROSAS) (VOLTA)': 137,
                'Oposto ao Espaço ADAV (VOLTA)': 142,
                'B. SÃO PEDRO (VOLTA)': 145,
                'B. LAGO AZUL (VOLTA)': 150,
                'Rua Tupã, 555 (VOLTA)': 151,
                'EE Professora Yolanda Martins (VOLTA)': 155,
                'Entrada Condomínio Quinta das Jangadas (VOLTA)': 160,
                'Fazenda do Rosário (Oposto a Pestalozzi) (VOLTA)': 165,
                'Hospital UPA (Av. São Paulo, 1081) (VOLTA)': 172,
                'Ibirité Integrado (VOLTA)': 175,
                'Fórum de Ibirité (VOLTA)': 178,
                'Perto da Prefeitura de Ibirité (VOLTA)': 181,
                'Terminal Ibirité (Plataforma C4) (VOLTA)': 184,
            }
        },
        'Sábado': {
            'horarios': ["04:45", "06:10", "06:50", "09:00", "11:10", "12:00", "14:15", "16:30", "18:45", "21:00"],
            'pontos': {
                'Terminal Ibirité': 0,
                'Perto da Prefeitura de Ibirité': 3,
                'Fórum de Ibirité': 6,
                'Ibirité Integrado': 9,
                'Hospital UPA': 12,
                'Fazenda do Rosário (Oposto a Pestalozzi)': 15,
                'Entrada Condomínio Quinta das Jangadas': 20,
                'B. LAGO AZUL': 21,
                'EE Professora Yolanda Martins': 26,
                'Rua Tupã, 555': 29,
                'B. SÃO PEDRO': 30,
                'Oposto ao Espaço ADAV': 36,
                'B. JARDIM DAS ROSAS': 30,
                'Perto de Magna/Thyssenkrupp': 35,
                'B. PETROVALE - BETIM (Rotatória Av. do Contorno)': 42,
                'GASMIG': 44,
                'Royal FIC': 47,
                'REGAP - Refinaria Gabriel Passos': 50,
                'CHEGADA À BR-381': 53,
                'Viaduto Torino': 57,
                'DEVA IVECO': 59,
                'CARREFOUR': 65,
                'Minas Máquinas - Mercedes-Benz': 70,
                'Jamef Transprtes': 76,
                'Viação Cometa': 80,
                'Leroy Merlin': 84,
                'Estação Eldorado': 87,
                'Marcopolo Contagem (VOLTA)': 97,
                'Estação Rio Nilo (VOLTA)': 102,
                'CARREFOUR (VOLTA)': 104,
                'DEVA IVECO (VOLTA)': 109,
                'Viaduto Torino (VOLTA)': 112,
                'SAÍDA DA BR-381': 117,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 120,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 125,
                'Perto de Magna/Thyssenkrupp': 129,
                'BAIRRO JARDIM DAS ROSAS (VOLTA)': 129,
                'Estação Eldorado': 87,
                'Leroy Merlin (VOLTA)': 90,
                'Minas Máquinas - Mercedes-Benz (VOLTA)': 104,
                'Estação Rio Nilo': 107,
                'CARREFOUR (VOLTA)': 108,
                'DEVA IVECO (VOLTA)': 113,
                'Viaduto Torino (VOLTA)': 117,
                'SAÍDA DA BR-381': 121,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 124,
                'Royal FIC (VOLTA)': 127,
                'GASMIG (VOLTA)': 130,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 132,
                'Perto de Magna/Thyssenkrupp (B. JARDIM DAS ROSAS) (VOLTA)': 137,
                'Oposto ao Espaço ADAV (VOLTA)': 142,
                'B. SÃO PEDRO (VOLTA)': 145,
                'B. LAGO AZUL (VOLTA)': 150,
                'Rua Tupã, 555 (VOLTA)': 151,
                'EE Professora Yolanda Martins (VOLTA)': 155,
                'Entrada Condomínio Quinta das Jangadas (VOLTA)': 160,
                'Fazenda do Rosário (Oposto a Pestalozzi) (VOLTA)': 165,
                'Hospital UPA (Av. São Paulo, 1081) (VOLTA)': 172,
                'Ibirité Integrado (VOLTA)': 175,
                'Fórum de Ibirité (VOLTA)': 178,
                'Perto da Prefeitura de Ibirité (VOLTA)': 181,
                'Terminal Ibirité (Plataforma C4) (VOLTA)': 184,
            }
        },
        'Domingo': {
            'horarios': ["04:45", "06:50", "09:20", "11:50", "14:20", "16:50", "19:20", "21:20"],
            'pontos': {
                'Terminal Ibirité': 0,
                'Perto da Prefeitura de Ibirité': 3,
                'Fórum de Ibirité': 6,
                'Ibirité Integrado': 9,
                'Hospital UPA': 12,
                'Fazenda do Rosário (Oposto a Pestalozzi)': 15,
                'Entrada Condomínio Quinta das Jangadas': 20,
                'B. LAGO AZUL': 21,
                'EE Professora Yolanda Martins': 26,
                'Rua Tupã, 555': 29,
                'B. SÃO PEDRO': 30,
                'Oposto ao Espaço ADAV': 36,
                'B. JARDIM DAS ROSAS': 30,
                'Perto de Magna/Thyssenkrupp': 35,
                'B. PETROVALE - BETIM (Rotatória Av. do Contorno)': 42,
                'GASMIG': 44,
                'Royal FIC': 47,
                'REGAP - Refinaria Gabriel Passos': 50,
                'CHEGADA À BR-381': 53,
                'Viaduto Torino': 57,
                'DEVA IVECO': 59,
                'CARREFOUR': 65,
                'Minas Máquinas - Mercedes-Benz': 70,
                'Jamef Transprtes': 76,
                'Viação Cometa': 80,
                'Leroy Merlin': 84,
                'Estação Eldorado': 87,
                'Marcopolo Contagem (VOLTA)': 97,
                'Estação Rio Nilo (VOLTA)': 102,
                'CARREFOUR (VOLTA)': 104,
                'DEVA IVECO (VOLTA)': 109,
                'Viaduto Torino (VOLTA)': 112,
                'SAÍDA DA BR-381': 117,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 120,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 125,
                'Perto de Magna/Thyssenkrupp': 129,
                'BAIRRO JARDIM DAS ROSAS (VOLTA)': 129,
                'Estação Eldorado': 87,
                'Leroy Merlin (VOLTA)': 90,
                'Minas Máquinas - Mercedes-Benz (VOLTA)': 104,
                'Estação Rio Nilo': 107,
                'CARREFOUR (VOLTA)': 108,
                'DEVA IVECO (VOLTA)': 113,
                'Viaduto Torino (VOLTA)': 117,
                'SAÍDA DA BR-381': 121,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 124,
                'Royal FIC (VOLTA)': 127,
                'GASMIG (VOLTA)': 130,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 132,
                'Perto de Magna/Thyssenkrupp (B. JARDIM DAS ROSAS) (VOLTA)': 137,
                'Oposto ao Espaço ADAV (VOLTA)': 142,
                'B. SÃO PEDRO (VOLTA)': 145,
                'B. LAGO AZUL (VOLTA)': 150,
                'Rua Tupã, 555 (VOLTA)': 151,
                'EE Professora Yolanda Martins (VOLTA)': 155,
                'Entrada Condomínio Quinta das Jangadas (VOLTA)': 160,
                'Fazenda do Rosário (Oposto a Pestalozzi) (VOLTA)': 165,
                'Hospital UPA (Av. São Paulo, 1081) (VOLTA)': 172,
                'Ibirité Integrado (VOLTA)': 175,
                'Fórum de Ibirité (VOLTA)': 178,
                'Perto da Prefeitura de Ibirité (VOLTA)': 181,
                'Terminal Ibirité (Plataforma C4) (VOLTA)': 184,
            }
        }
    },

    #LINHA 1620
    '1620 (Jardim Das Rosas / Estação Eldorado) - Tarifa: R$ 8,20': {  
        'Dia útil': {
            'horarios': ["04:50", "06:00", "09:30", "11:30", "13:30", "15:30", "16:30", "18:30", "19:30"],
            'pontos': {
                'B. JARDIM DAS ROSAS': 0,
                'Perto de Magna/Thyssenkrupp': 5,
                'B. PETROVALE - BETIM (Rotatória Av. do Contorno)': 12,
                'GASMIG': 14,
                'Royal FIC': 17,
                'REGAP - Refinaria Gabriel Passos': 20,
                'CHEGADA À BR-381': 23,
                'Viaduto Torino': 27,
                'DEVA IVECO': 29,
                'CARREFOUR': 35,
                'Minas Máquinas - Mercedes-Benz': 40,
                'Jamef Transprtes': 46,
                'Viação Cometa': 50,
                'Leroy Merlin': 54,
                'Estação Eldorado': 57,
                'Marcopolo Contagem (VOLTA)': 67,
                'Estação Rio Nilo (VOLTA)': 72,
                'CARREFOUR (VOLTA)': 74,
                'DEVA IVECO (VOLTA)': 79,
                'Viaduto Torino (VOLTA)': 82,
                'SAÍDA DA BR-381': 87,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 90,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 95,
                'Perto de Magna/Thyssenkrupp': 99,
                'BAIRRO JARDIM DAS ROSAS (VOLTA)': 99,
                'Estação Eldorado': 57,
                'Leroy Merlin (VOLTA)': 60,
                'Minas Máquinas - Mercedes-Benz (VOLTA)': 74,
                'Estação Rio Nilo': 77,
                'CARREFOUR (VOLTA)': 78,
                'DEVA IVECO (VOLTA)': 83,
                'Viaduto Torino (VOLTA)': 87,
                'SAÍDA DA BR-381': 91,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 94,
                'Royal FIC (VOLTA)': 97,
                'GASMIG (VOLTA)': 100,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 102,
                'Perto de Magna/Thyssenkrupp (B. JARDIM DAS ROSAS) (VOLTA)': 107,
                'B. JARDIM DAS ROSAS (VOLTA)': 112,
            }
        },
        'Sábado': {
            'horarios': ["05:00", "06:50", "09:20", "11:40", "14:00", "16:20", "19:00"],
            'pontos': {
                'B. JARDIM DAS ROSAS': 0,
                'Perto de Magna/Thyssenkrupp': 5,
                'B. PETROVALE - BETIM (Rotatória Av. do Contorno)': 12,
                'GASMIG': 14,
                'Royal FIC': 17,
                'REGAP - Refinaria Gabriel Passos': 20,
                'CHEGADA À BR-381': 23,
                'Viaduto Torino': 27,
                'DEVA IVECO': 29,
                'CARREFOUR': 35,
                'Minas Máquinas - Mercedes-Benz': 40,
                'Jamef Transprtes': 46,
                'Viação Cometa': 50,
                'Leroy Merlin': 54,
                'Estação Eldorado': 57,
                'Marcopolo Contagem (VOLTA)': 67,
                'Estação Rio Nilo (VOLTA)': 72,
                'CARREFOUR (VOLTA)': 74,
                'DEVA IVECO (VOLTA)': 79,
                'Viaduto Torino (VOLTA)': 82,
                'SAÍDA DA BR-381': 87,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 90,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 95,
                'Perto de Magna/Thyssenkrupp': 99,
                'BAIRRO JARDIM DAS ROSAS (VOLTA)': 99,
                'Estação Eldorado': 57,
                'Leroy Merlin (VOLTA)': 60,
                'Minas Máquinas - Mercedes-Benz (VOLTA)': 74,
                'Estação Rio Nilo': 77,
                'CARREFOUR (VOLTA)': 78,
                'DEVA IVECO (VOLTA)': 83,
                'Viaduto Torino (VOLTA)': 87,
                'SAÍDA DA BR-381': 91,
                'REGAP - Refinaria Gabriel Passos (VOLTA)': 94,
                'Royal FIC (VOLTA)': 97,
                'GASMIG (VOLTA)': 100,
                'Rotatória Av. do Contorno - B. PETROVALE (VOLTA)': 102,
                'Perto de Magna/Thyssenkrupp (B. JARDIM DAS ROSAS) (VOLTA)': 107,
                'B. JARDIM DAS ROSAS (VOLTA)': 112,
            }
        },
        'Domingo (FORA DE OPERAÇÃO)': {
            'horarios': [],
            'pontos': {

            }
        }
    },
}